/**
 * <p>This package contains Vite's JSP standard tag library for JSP 2.0+.
 * Supports JSP view implementations within Spring's Web MVC framework.
 * For more details on each tag, see the list of tags below with links to
 * individual tag classes, or check the {@code vite.tld} file:
 *
 * <ul>
 * <li>{@link com.javite.spring.tags.ViteImport The import tag}
 * </ul>
 *
 * <p>Please note that the various tags generated by this form tag library are
 * compliant with https://www.w3.org/TR/xhtml1/ and attendant
 * https://www.w3.org/TR/xhtml1/dtds.html#a_dtd_XHTML-1.0-Strict.
 */
@NonNullApi
@NonNullFields
package com.javite.spring.tags;

import org.springframework.lang.NonNullApi;
import org.springframework.lang.NonNullFields;
