name: "Main Pipeline"

on:
    push:
        branches: [ "main" ]
        tags:
            - '*'
    pull_request:
        branches: [ '*' ]

jobs:

    build:
        permissions:
            contents: read
            checks: write
            id-token: write
        name: Build + unit tests
        uses: ./.github/workflows/callable.build.yml
        if: | # avoid unnecessary pipeline runs during artifact release process ('gradle release plugin')
            !contains(github.event.head_commit.message, 'chore: release v')
            || github.ref_type == 'tag'

    code_analysis:
        name: Code Analysis (multi)
        permissions:
            actions: read
            contents: read
            security-events: write
        uses: ./.github/workflows/callable.code-analysis.yml
        needs: build
        if: |
            github.event_name != 'workflow_dispatch'
            || inputs.type == '...no release'

    #  integration_test:
    #    name: Integration tests
    #    uses: ./.github/workflows/callable.integration-test.yml
    #    needs: build

    publish_central_portal:
        name: Publish artifact (Maven Central)
        uses: ./.github/workflows/callable.publish-central-portal.yml
        secrets: inherit
        needs: build
        if: |
            (
              github.event_name != 'workflow_dispatch'
              || inputs.type == '...no release'
            ) && (
              github.ref == 'refs/heads/main'
              || github.ref_type == 'tag'
            )

    publish_dokka:
        name: Publish dokka (GitHub Pages)
        permissions:
            contents: write
        uses: ./.github/workflows/callable.publish-dokka.yml
        needs: [build, publish_central_portal]
        if: |
            (
              github.ref == 'refs/heads/main'
              && ( inputs.type == '' || inputs.type == '...no release' )
            ) || github.ref_type == 'tag'
