name: Publish to Sonatype (Maven Central)
on:
    workflow_call:

jobs:
    publish:
        name: gradle publish (Maven Central)
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout project sources
                uses: actions/checkout@v4

            -   uses: actions/setup-java@v4
                with:
                    distribution: 'corretto'
                    java-version: '21'
            -   uses: gradle/actions/wrapper-validation@v3
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3.3.2
                with:
                    cache-read-only: true

            # note the following two steps are identical but different names for better DX in GitHub Actions UI
            -   name: Publish SNAPSHOT to Central Portal
                if: github.ref == 'refs/heads/main'
                run: ./gradlew publishAllPublicationsToMavenCentralRepository
                env:
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.mavenCentralUsername }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.mavenCentralPassword }}
                    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signingInMemoryKey }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.signingInMemoryKeyId }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signingInMemoryKeyPassword }}
            -   name: Publish RELEASE to Central Portal
                if: github.ref_type == 'tag'
                run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
                env:
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.mavenCentralUsername }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.mavenCentralPassword }}
                    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signingInMemoryKey }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.signingInMemoryKeyId }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signingInMemoryKeyPassword }}
