name: Publish dokka (GitHub Pages)

on:
    workflow_dispatch:
    workflow_call:

jobs:
    build_package_dokka:
        name: Generate Dokka
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            -   name: Checkout project sources
                uses: actions/checkout@v4

            -   uses: actions/setup-java@v4
                with:
                    distribution: 'corretto'
                    java-version: '21'
            -   uses: gradle/actions/wrapper-validation@v3
            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v3.3.2
                with:
                    cache-read-only: true

#            -   name: Generate javadoc (gradle)
#                run: ./gradlew javadoc

            -   name: Generate dokka HTML documentation
                run: ./gradlew dokkaHtmlMultiModule

            -   name: Conclude dokka version and set env
                run: |
                    if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/master" ]]; then
                      echo "PUBLISH_VERSION=current" >> $GITHUB_ENV
                    else
                      echo "PUBLISH_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
                    fi

            -   name: Conclude library name and set env
                run: echo "LIBRARY_NAME=$(grep -o '^rootProject.name.*' settings.gradle.kts | sed -e 's/rootProject.name.*"\(.*\)"/\1/')" >> $GITHUB_ENV

            -   name: zip dokka folder
                env:
                    LIBRARY_NAME: ${{ env.LIBRARY_NAME }}
                run: |
                    cd "build/dokka/htmlMultiModule"
                    zip -r ../../../dokka.zip .

            -   name: Upload artifact
                uses: actions/upload-artifact@v4
                with:
                    name: dokka.zip
                    path: dokka.zip

    deploy_dokka:
        name: Deploy (GH Pages)
        runs-on: ubuntu-latest
        needs: build_package_dokka
        permissions:
            contents: write
        steps:
            -   name: Checkout project sources
                uses: actions/checkout@v4
                with:
                    ref: main
                    token: ${{ secrets.CI_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}

            -   name: Checkout or create empty branch 'gh-pages'
                run: |
                    git fetch origin gh-pages || true
                    git checkout gh-pages || git switch --orphan gh-pages

            -   name: Conclude dokka version and set env
                run: |
                    if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/master" ]]; then
                      echo "PUBLISH_VERSION=current" >> $GITHUB_ENV
                    else
                      echo "PUBLISH_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
                    fi

            -   name: Create root index redirect
                env:
                    GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
                run: |
                    echo "<!DOCTYPE html><html lang=en><meta content=\"text/html; charset=utf-8\"http-equiv=Content-Type><meta content=\"index redirect\"name=description><link href=/$GITHUB_REPOSITORY_NAME/docs/ rel=canonical><link href=stylesheet.css rel=stylesheet title=Style><script>window.location.replace(\"/$GITHUB_REPOSITORY_NAME/docs/\")</script><noscript><meta content=0;/$GITHUB_REPOSITORY_NAME/docs/ http-equiv=Refresh></noscript><main role=main><noscript><p>JavaScript is disabled on your browser.</p></noscript><p><a href=/$GITHUB_REPOSITORY_NAME/docs/ >/$GITHUB_REPOSITORY_NAME/docs/</a></main>" > index.html

            -   name: Download artifact from build job
                uses: actions/download-artifact@v4
                with:
                    name: dokka.zip

            -   name: unzip dokka folder
                env:
                    PUBLISH_VERSION: ${{ env.PUBLISH_VERSION }}
                run: |
                    mkdir -p docs
                    rm -Rf "docs/$PUBLISH_VERSION" || true
                    unzip -d "docs/$PUBLISH_VERSION" dokka.zip
                    rm dokka.zip

            -   name: Create dokka index.html listing versions
                env:
                    PUBLISH_VERSION: ${{ env.PUBLISH_VERSION }}
                    GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
                run: |
                    mkdir -p docs
                    rm docs/index.html || true
                    touch docs/index.html
                    
                    versions=( $(cd docs && find . -maxdepth 1 -type d | jq -srR 'split("\n") | unique | .[][2:] | select(length > 0)') )
                    
                    echo "docs versions:"
                    for value in "${versions[@]}"
                    do
                      echo "- $value"
                    done
                    
                    echo "<!DOCTYPE HTML>" >> docs/index.html
                    echo "<html lang=\"en\">" >> docs/index.html
                    echo "<head>" >> docs/index.html
                    echo "    <title>Dokka | '$GITHUB_REPOSITORY_NAME'</title>" >> docs/index.html
                    echo "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">" >> docs/index.html
                    echo "    <meta charset=\"UTF-8\">" >> docs/index.html
                    echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> docs/index.html
                    echo "    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">" >> docs/index.html
                    echo "    <meta name=\"description\" content=\"Dokka for library '$GITHUB_REPOSITORY_NAME'\">" >> docs/index.html
                    echo "</head>" >> docs/index.html
                    echo "<body>" >> docs/index.html
                    echo "<main style=\"font-family: sans-serif;\">" >> docs/index.html
                    echo "    <h1>Dokka</h1>" >> docs/index.html
                    echo "    <h2>Versions</h2>" >> docs/index.html
                    echo "    <ul>" >> docs/index.html
                    
                    for value in "${versions[@]}"
                    do
                      echo "        <li><a href=\"$value\">$value</a></li>" >> docs/index.html
                    done
                    
                    echo "    </ul>" >> docs/index.html
                    echo "</main>" >> docs/index.html
                    echo "</body>" >> docs/index.html
                    echo "</html>" >> docs/index.html

            -   name: Commit files
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    git add .
                    git status
                    git diff-index --quiet HEAD || git commit -m "chore: updates index.html files incl. dokka versions"

            # Push changes
            -   name: Push changes
                run: |
                    git push --set-upstream origin gh-pages
